from __future__ import annotations

import smtplib
from typing import Any
from pathlib import Path
from config import settings
from utils.logging import logger
from email.message import EmailMessage
from jinja2 import Environment, FileSystemLoader, select_autoescape


BASE_DIR = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = BASE_DIR / "reports" / "templates"
TEMP_DIR = Path(settings.REPORT_TEMP_DIR or BASE_DIR / "reports" / "temp")
REPORT_DIR = Path(settings.REPORT_OUTPUT_DIR or BASE_DIR / "reports" / "output")

ENV = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(["html", "xml"]),
)

REPORT_TEMPLATES = {
    "executive_summary": "executive_summary.html",
    "latest_backup": "latest_backup_report.html",
    "failure_investigation": "failure_investigation.html",
}

def render_report_html(report_type: str, report_data: dict[str, Any]) -> str:
    template_name = REPORT_TEMPLATES.get(report_type)
    if not template_name:
        raise ValueError(f"Unsupported report type: {report_type}")

    template = ENV.get_template(template_name)
    return template.render(report=report_data)

# send email with the given subject, recipients, html body and attachments (if any)
def send_email(
    subject: str,
    recipients: list[str],
    html_body: str,
    attachments: list[Path] | None = None,
) -> None:
    if not settings.SMTP_HOST or not settings.SMTP_PORT or not settings.SMTP_FROM:
        raise RuntimeError("SMTP_HOST, SMTP_PORT, and SMTP_FROM must be configured to send email.")

    # create an email message with the given subject, recipients and html body
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = settings.SMTP_FROM
    message["To"] = ", ".join(recipients)
    message.set_content("This email is generated by the Agentic Observatory. Please view in an HTML compatible email viewer.")
    message.add_alternative(html_body, subtype="html")

    # add attachments to the email if provided
    # for each attachment, read the file and add it to the email 
    # with the appropriate maintype and subtype based on the file extension
    attachments = attachments or []
    for attachment in attachments:
        if not attachment.exists():
            continue
        data = attachment.read_bytes()
        maintype = "application"
        subtype = attachment.suffix.lstrip(".") or "octet-stream"
        message.add_attachment(
            data,
            maintype=maintype,
            subtype=subtype,
            filename=attachment.name,
        )

    # send the email using the SMTP server configured in settings
    if settings.SMTP_PORT == 465:
        smtp_client = smtplib.SMTP_SSL(settings.SMTP_HOST, settings.SMTP_PORT)
    else:
        smtp_client = smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT)
        smtp_client.starttls()

    # if SMTP_USERNAME and SMTP_PASSWORD are set, login to the SMTP server before sending the email
    try:
        if settings.SMTP_USERNAME and settings.SMTP_PASSWORD:
            smtp_client.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
        smtp_client.send_message(message)
    finally:
        smtp_client.quit()

# converts input into a clean list of email strings.
def normalize_recipients(value: list[str] | str) -> list[str]:
    if isinstance(value, str):
        return [item.strip() for item in value.split(",") if item.strip()]
    return [item.strip() for item in value if item.strip()]
